.gitignore
.prettierrc

- 공통 prettier 설정 추가
EPIC: #0
* 백엔드와 프론트엔드에서 공통적으로 사용할 prettier를 설정했습니다.
* prettier 설정
* 없음
* 없음
* 없음
#
---

chore: prettier

---

.prettierrc
apps/backend/.prettierrc

- 공통 prettier 설정 추가
EPIC: #0
* 백엔드와 프론트엔드에서 공통적으로 사용할 prettier를 설정했습니다.
* prettier 설정
* 없음
* 없음
* 없음
#
---

chore: prettier 설정 변경

---

apps/frontend/src/pages/MainPage.tsx
apps/frontend/src/pages/QuizZoneWaitingPage.tsx

* 공통 컴포넌트를 활용하여 메인페이지와 퀴즈 대기실 페이지를 구현 하였습니다.
*
* 없음
*
*
#
---
close #2

Feature/#2 메인페이지, 퀴즈 대기실 페이지 

---

apps/frontend/src/pages/MainPage.tsx
apps/frontend/src/pages/QuizWaitingPage.tsx
apps/frontend/src/pages/QuizZoneWaitingPage.tsx

* 퀴즈 풀이 대기 페이지를 임시로 구현 하였습니다. 
* 관련 TASK #5 
* 공통 컴포넌트를 활용하여서 퀴즈 풀이 대기 페이지를 구현 했습니다.
* 구현 과정에서 TimerDisplay를 통해서 제공 받은 시간을 기준으로 풀이 페이지를 넘어가는데 얼마나 남았는 지 확인 할 수 있도록 구현 했습니다. 
*
*
*
* P2 : 반영을 적극적으로 고려해 주시면 좋을 …

Feature/#5 퀴즈 풀이 대기 페이지 

---

apps/frontend/src/pages/MainPage.tsx
apps/frontend/src/pages/QuizResultPage.tsx
apps/frontend/src/pages/QuizWaitingPage.tsx
apps/frontend/src/pages/QuizZonePage.tsx
apps/frontend/src/pages/QuizZoneWaitingPage.tsx
apps/frontend/src/pages/RootLayout.tsx
apps/frontend/src/router/router.tsx

* 퀴즈 풀이 페이지 구현
* 퀴즈 결과 페이지 구현
* 임시로 풀이 페이지에서 결과 페이지로 이동할 수 있도록 버튼 추가
* 임시로 결과 페이지에서 메인 페이지로 이동할 수 있도록 버튼 추가
*
*
*
# …

Feature/#8 퀴즈 풀이 페이지 및 퀴즈 결과 페이지 임시 구현

---

apps/frontend/package.json
apps/frontend/src/components/common/CustomAlert.stories.tsx
apps/frontend/src/components/common/CustomAlert.tsx
apps/frontend/src/components/ui/alert-dialog.tsx
pnpm-lock.yaml

* 공통 컴포넌트에 해당하는 CustomAlert을 구현 하였습니다. 
#

Feature/#51 CustomAlert

---

apps/frontend/src/components/common/TextCopy.stories.tsx
apps/frontend/src/components/common/TextCopy.tsx
apps/frontend/src/components/common/Typogrpahy.tsx

* 텍스트 복사 컴포넌트를 구현하였습니다.
* 텍스트에 관련된 상태는 해당 컴포넌트를 사용하는 부모 컴포넌트에서 관리하고 해당 컴포넌트에서는 온전히 텍스트 복사에 대한 역할만 하게 됩니다. 
#
---

Feature/#52 텍스트 복사 컴포넌트 

---

apps/frontend/src/hook/useQuizZoneManager.tsx
apps/frontend/src/hook/useTimer.ts

Feature/#56 퀴즈존 퍼널 컴포넌트 구현

---

.github/workflows/deploy-be.yml
.github/workflows/deploy-static.yml
.github/workflows/test.yml
apps/backend/.dockerignore
apps/backend/Dockerfile
apps/backend/package.json
apps/backend/tsconfig.json
apps/frontend/package.json
apps/frontend/tailwind.config.cjs
package.json
typedoc.json

- github develop, main에 PR 올릴 시 test 코드 수행되도록 구현
TASK: #48
PR 올릴 시에 test 코드가 수행되도록 github action 구현
*
*
*
*
#
---

chore: github workflows 구현

---

apps/backend/src/play/play.gateway.ts

- gateway @MessageBody 설정 오류 수정
Story: #3
Task: #5
* PlayGateway의 submit 이벤트 처리의 메시지 형식을 지정하는 부분의 설정 오류로인해 데이터를 받지 못하는 문제 해결
* @MessageBody 데코레이터의 인자 `data` 제거

fix: submit 에러 수정

---

.github/workflows/deploy-be.yml
.github/workflows/deploy-fe.yml
.github/workflows/test.yml
apps/frontend/src/blocks/QuizZone/QuizInProgress.tsx
apps/frontend/src/components/common/CustomAlert.stories.tsx
apps/frontend/src/hook/useQuizZoneManager.tsx

- develop develop 브랜치에 PR 트리거로 엔진엑스 서버에 배포되도록 설정
Task: #60
프론트엔드 배포용 yml 파일 작성
deploy-fe.yml

chore: 프론트엔드 배포용 yml 파일 작성

---

apps/backend/package.json
apps/backend/src/main.ts
apps/backend/src/play/dto/current-quiz.dto.ts
apps/backend/src/play/play.gateway.ts
apps/backend/src/play/play.service.ts
apps/backend/src/quiz-zone/dto/create-quiz-zone.dto.ts
apps/backend/src/quiz-zone/dto/waiting-quiz-zone.dto.ts
apps/backend/src/quiz-zone/quiz-zone.controller.ts
apps/backend/src/quiz-zone/quiz-zone.service.ts
apps/backend/src/quiz-zone/repository/quiz-zone.repository.interface.ts
pnpm-lock.yaml

- 백엔드 작업 영역 전반 tsdoc 적용
- 컨트롤러 및 dto swagger 적용
* 컨트롤러 및 DTO Swagger 반영
* 서비스 영역 tsdoc 반영

docs: tsdoc, swagger

---

apps/backend/config/http.config.ts
apps/backend/package.json
apps/backend/src/app.module.ts
apps/backend/src/main.ts
pnpm-lock.yaml

* 실행 환경별 설정 분리를 위한 ConfigModule 반영
* 백엔드 환경 변수를 backend/config 디렉토리 아래에서 설정할 수 있도록 구성했습니다.
* 이후 환경 변수 추가시 `config/http.config.ts` 와 같은 형식으로 파일을 구성해주시면 됩니다.
* 환경 변수 파일은 `App.module.ts`에 설정을 추가해주시면 됩니다.
* 환경 별 설정이 다른 경우 `main.ts`내 `switch` 문 내부의 환경에 따라 설정들을 추가해주시면 됩니다.

chore: 환경 변수 설정

---

.github/workflows/deploy-be.yml
.github/workflows/deploy-fe.yml
apps/backend/Dockerfile

feat: 환경변수 설정

---

.github/workflows/deploy-fe.yml

feat: env 수정

---

.github/workflows/deploy-be.yml
.github/workflows/deploy-static.yml
apps/backend/Dockerfile
ecosystem.config.cjs

- docker run 할 때 main.js 파일을 못잡는 오류를 수정하였습니다.

hotfix: 배포 오류 수정

---

apps/frontend/package.json
apps/frontend/src/blocks/QuizZone/QuizWaiting.tsx
apps/frontend/src/blocks/QuizZone/QuizZoneLobby.tsx
apps/frontend/src/components/common/CommonButton.tsx
apps/frontend/src/components/common/ContentBox.tsx
apps/frontend/src/components/common/CustomAlert.tsx
apps/frontend/src/components/common/TextCopy.tsx
apps/frontend/src/components/ui/avatar.tsx
apps/frontend/src/pages/MainPage.tsx
pnpm-lock.yaml

이 PR은 퀴즈 대기 화면의 사용자 경험과 시각적 완성도를 개선하는 것을 목적으로 합니다. 구체적으로:
1. 다양한 디바이스에서의 최적화된 레이아웃 제공
2. 타이머 정보의 가독성과 정확성 향상
3. 시각적 계층 구조를 통한 정보 전달력 강화
4. 전반적인 UI 요소들의 간격과 크기 최적화
- 기본 너비를 화면의 4/5로 설정
- 중간 크기(md) 이상의 화면에서 48rem으로 최적화
- 컴포넌트 간 간격을 gap-8로 조정하여 시각적 여백 개선
- null 체크를 통한 안정적인 조건부 렌더링 구현
- 소수점 첫째자리까지 표시하여 정확한 시간 정보 제공
- "초 뒤에 시작" 텍스트 추가로 직관적인 정보 전달
- 안내 문구 크기를 3xl에서 2xl로 조정하여 적절한 시각적 비중 부여
- 색상을 blue에서 gray로 변경하여 가독성과 시각적 계층 구조 개선
- 전체적인 타이포그래피 일관성 확보
close #23
close #27

Feature/#24,#23,#27 🎨 퀴즈 대기 화면 UI/UX 개선 및 타이머 표시 기능 강화

---

apps/frontend/package.json
apps/frontend/src/blocks/QuizZone/QuizInProgress.tsx
apps/frontend/src/blocks/QuizZone/QuizWaiting.tsx
apps/frontend/src/blocks/QuizZone/QuizZoneLobby.tsx
apps/frontend/src/components/common/CommonButton.tsx
apps/frontend/src/components/common/ContentBox.tsx
apps/frontend/src/components/common/CustomAlert.tsx
apps/frontend/src/components/common/Input.tsx
apps/frontend/src/components/common/ProgressBar.tsx
apps/frontend/src/components/common/TextCopy.tsx
apps/frontend/src/components/ui/avatar.tsx
apps/frontend/src/pages/MainPage.tsx
pnpm-lock.yaml

이 PR은 퀴즈 진행 중 화면의 사용자 경험을 개선하고 있습니다. 구체적으로:
1. 프로그래스바의 정보 전달력 향상
2. 단답형 문제에서의 답안 제출 방식 개선
3. 사용자 편의성 증대를 위한 인터페이스 개선
관련 이슈: #9, #10, #15
- 프로그래스바에 남은 시간 문구 추가로 직관성 향상
- ContentBox 컴포넌트의 반응형 레이아웃 적용
- 모바일: 화면 너비의 4/5
- 태블릿/데스크톱: 최소 너비 48rem
- 타이포그래피를 활용한 문제 텍스트 강조
- 단답형 문제에서 Enter 키 입력으로 답안 제출 가능
- Input 컴포넌트 onKeyDown 이벤트 핸들러 추가
- 객관식 문제의 경우 선택지 클릭으로 즉시 제출
- 재사용 가능한 공통 컴포넌트 활용
- CommonButton
- ContentBox
- Input
- ProgressBar
- Typography

Feature/#9,#10,#15  ✨ 퀴즈 진행 화면 UX 개선 및 답안 제출 방식 강화

---

.github/workflows/deploy-be.yml
.github/workflows/deploy-fe.yml

- 환경변수를 environment에 따라 분리
#84
스테이징 환경을 만들어 배포 환경과 동일한 환경에서 테스트 해볼 수 있도록 테스트 서버를 띄워서 진행하기 위해 github action을 수정하였다.
github에서 environment에 따라 환경변수를 분리할 수 있어 환경변수에 맞는 값이 들어갈 수 있도록 수정하였다.

chore: staing 환경 구축을 위한 코드 수정

---

apps/backend/package.json
apps/backend/src/app.controller.spec.ts
apps/backend/src/app.module.ts
apps/backend/src/app.service.ts
apps/backend/src/logger/http-logger.middleware.ts
apps/backend/src/logger/winston.config.ts
pnpm-lock.yaml

* 백엔드 로거 반영 및 설정 추가
* Winston 사용 처리 추가
* Winston 설정 파일 추가
* 로거 활용 예시 추가
* http-logger.middleware.ts는 미들웨어를 통해 로거를 활용하는 예시입니다.
* app.service.ts는 서비스에서 로거를 활용하는 예시입니다.
* app.controller.spec.ts는 winston 모듈을 모킹하여 테스트 의존성을 제거한 예시입니다.

chore: winston 반영 및 예시 추가

---

.github/workflows/deploy-be.yml
.github/workflows/deploy-fe.yml
apps/backend/src/main.ts

* 코드가 반영될 때마다 변경되지 않은 영역도 stg, prod에 배포되는 문제 해결
* github action 배포 yaml에 paths를 지정하여 해당 영역의 변경이 있을때 동작하도록 하였습니다.

chore: github action 설정 변경

---

apps/backend/src/play/play.gateway.ts
apps/backend/src/play/play.service.ts
apps/backend/src/quiz-zone/quiz-zone.service.spec.ts
apps/backend/src/quiz-zone/quiz-zone.service.ts
apps/backend/src/quiz-zone/repository/quiz-zone.memory.repository.spec.ts
apps/backend/src/quiz-zone/repository/quiz-zone.memory.repository.ts
apps/backend/src/quiz-zone/repository/quiz-zone.repository.interface.ts

* 퀴즈존 리포지토리 구조 변경
* 퀴즈존 리포지토리 구조 변경
* 퀴즈존 리포지토리 테스트 수정
* 퀴즈존 서비스 관련 처리 수정 및 개선
* 플레이 서비스 관련 처리 수정 및 개선
* 플레이 게이트웨이 관련 처리 수정 및 개선

refactor: 퀴즈존 리포지토리 리펙토링

---

.github/workflows/deploy-backend.yml
.github/workflows/deploy-frontend.yml
apps/backend/src/quiz-zone/dto/find-quiz-zone.dto.ts
apps/frontend/src/pages/QuiZonePage.tsx

chore: github action 수정

---

apps/backend/src/core/SessionWsAdapter.ts
apps/backend/src/main.ts

* 웹소켓 연결 및 메시지 송수신에서 사용자 권한 여부 확인 처리를 위한 Guard 적용
* WsAdapter 커스터마이징을 통해 웹소켓 클라이언트의 session 연결
* 
* 세션을 함께 사용하는 웹소켓 클라이언트를 위한 인터페이스가 추가되었습니다. 
* 
* 웹소켓 클라이언트에서 세션을 사용하기 위해 기존 `WebSocket` 인터페이스를 새롭게 추가된 `WebSocketWithSession` 인터페이스로 변경이 필요합니다.

[Chore] 백엔드 WebSocketAdapter 커스터마이징

---

.github/workflows/deploy-backend.yml
.github/workflows/deploy-frontend.yml
.github/workflows/test-backend.yml
.github/workflows/test-frontend.yml

- test와 deploy 분리
- test는 pull_request될 때 실행
- deploy는 push될 때 실행

chore: test, deploy 분리

---

apps/backend/.gitignore
apps/backend/src/common/constants.ts
apps/backend/src/play/play.service.spec.ts
apps/backend/src/quiz-zone/dto/create-quiz-zone.dto.ts
apps/backend/src/quiz/dto/create-quiz-request.dto.ts
apps/backend/src/quiz/dto/search-quiz-set-request.dto.ts
apps/backend/src/quiz/quiz.controller.spec.ts
apps/backend/src/quiz/quiz.controller.ts
apps/backend/src/quiz/quiz.service.spec.ts
apps/backend/src/quiz/quiz.service.ts
apps/backend/test/quiz.e2e-spec.ts
apps/frontend/src/blocks/CreateQuizZone/CandidateQuizzes.tsx
apps/frontend/src/blocks/CreateQuizZone/CreateQuiz.tsx
apps/frontend/src/blocks/CreateQuizZone/CreateQuizSet.tsx
apps/frontend/src/blocks/CreateQuizZone/CreateQuizZoneBasic.tsx
apps/frontend/src/blocks/CreateQuizZone/SearchQuizSet.tsx
apps/frontend/src/blocks/CreateQuizZone/SearchQuizSetResults.tsx
apps/frontend/src/constants/quiz-set.constants.ts
apps/frontend/src/hook/quizZone/useQuizZone.tsx
apps/frontend/src/hook/useValidInput.ts
apps/frontend/src/pages/CreateQuizZonePage.tsx
apps/frontend/src/pages/MainPage.tsx
apps/frontend/src/router/router.tsx
apps/frontend/src/types/create-quiz-zone.types.ts
apps/frontend/src/types/quizZone.types.ts
apps/frontend/src/utils/requests.ts
apps/frontend/src/utils/validators.ts

* 퀴즈존 만들기 기능 구현
* 퀴즈셋 만들기 기능 구현
* 퀴즈존 생성 컴포넌트 구현
* 퀴즈셋 생성 컴포넌트 구현
* useValidState 커스텀 훅 구현

[FE] 퀴즈존 생성 처리 및 퀴즈셋 생성 처리 구현

---

README.md
apps/backend/README.md
apps/frontend/README.md

docs: 메인, 프론트, 백엔드 리드미 수정

---

apps/frontend/src/blocks/QuizZone/QuizZoneResult.tsx
apps/frontend/src/types/quizZone.types.ts

fix: ui 랭킹 점수 수정

---

apps/frontend/src/hook/quizZone/useQuizZone.tsx
apps/frontend/src/types/quizZone.types.ts

fix: FE 이벤트 데이터 수신 처리 수정

---

apps/backend/src/quiz-zone/dto/create-quiz-zone.dto.ts
apps/backend/src/quiz-zone/quiz-zone.controller.ts
apps/backend/src/quiz/dto/create-quiz-request.dto.ts
apps/frontend/src/components/common/CustomAlert.tsx
apps/frontend/src/components/common/CustomAlertDialogContent.tsx
apps/frontend/src/hook/quizZone/useQuizZone.tsx
apps/frontend/src/pages/MainPage.tsx

* 퀴즈존 입장 전 확인 알럿 추가
* 공용 얼럿 컴포넌트 일부 로직 변경
* 퀴즈존 입장시 이전 참여중인 퀴즈존이 아닐 경우 얼럿 노출
* 퀴즈셋 생성 시 누락된 퀴즈 개수 검증 조건 추가
* 퀴즈존 생성 시 설명 검증 조건 정책대로 수정

퀴즈존 입장시 기존 퀴즈존이 아닐 경우 얼럿 노출

---

apps/backend/src/quiz-zone/dto/find-quiz-zone.dto.ts
apps/backend/src/quiz-zone/quiz-zone.service.spec.ts
apps/backend/src/quiz-zone/quiz-zone.service.ts
apps/backend/src/quiz/quiz.service.spec.ts
apps/backend/src/quiz/quiz.service.ts
apps/frontend/src/blocks/QuizZone/QuizZoneLobby.tsx
apps/frontend/src/hook/quizZone/useQuizZone.tsx
apps/frontend/src/pages/QuizZonePage.tsx
apps/frontend/src/types/quizZone.types.ts

Story: #212
* 로비에서 정원이 현재 인원과 함께 출력
* 
* 자료구조 및 파라미터 수정
* 일부 로직 수정
* 없음

[Feature] 로비에서 퀴즈존 최대인원 확인

---

apps/backend/src/play/play.service.ts
apps/frontend/src/blocks/QuizZone/QuizWaiting.tsx
apps/frontend/src/blocks/QuizZone/QuizZoneResult.tsx

[Fix] 소수점 자르기, 띄어쓰기 허용

---

README.md

docs: 리드미 아키텍처, 기능, 설명 업데이트

---

apps/frontend/src/blocks/CreateQuizZone/CreateQuiz.tsx
apps/frontend/src/blocks/CreateQuizZone/CreateQuizSet.tsx
apps/frontend/src/blocks/CreateQuizZone/CreateQuizZoneBasic.tsx
apps/frontend/src/blocks/QuizZone/QuizZoneResult.tsx
apps/frontend/src/components/common/Input.tsx
apps/frontend/src/pages/MainPage.tsx
apps/frontend/src/pages/QuizZonePage.tsx
apps/frontend/src/utils/validators.ts

사용자 인터페이스의 여러 부분에서 발견된 UI/UX 관련 이슈들을 개선하고자 합니다. 특히 validationError 메시지 표시, 글자 수 제한 기능, 그리고 결과 페이지의 타이머 정렬 등에 대한 사용자 경험 개선이 필요했습니다.
1. ValidationError 메시지 개선
- 에러 메시지 문구를 보다 명확하게 수정
- 글자 수와 에러 메시지가 같은 라인에 표시되도록 레이아웃 조정
- 최대 글자 수 제한 기능 구현
2. 결과 페이지 UI 개선
- 타이머 요소를 중앙 정렬하도록 수정
- isResult 조건 로직 단순화
- 불필요한 문구 제거를 통한 인터페이스 정리
- 문구의 세부 내용 일부 변경
1. ValidationError 메시지와 글자 수 표시가 같은 라인에 위치한 것이 UX 관점에서 적절한지 검토 부탁드립니다.
2. 최대 글자 수 제한 값이 적절하게 설정되었는지 확인 부탁드립니다.
3. 타이머 중앙 정렬이 모든 화면 크기에서 정상적으로 작동하는지 확인 부탁드립니다.
1. 글자 수 제한 기능
- 최대 글자 수 초과 시 에러 메시지 표시 확인
- 글자 수 카운팅이 정확한지 확인
2. 결과 페이지
- 다양한 디바이스에서 타이머 중앙 정렬 확인
- isResult 조건 제거 후 페이지 동작 검증

Feature/conflict UI fix

---

README.md
package.json

ISSUE: #223
- README 추가
- pacakge.json start 설정 추가

docs: README 추가, package.json 추가

---

apps/backend/src/quiz-zone/dto/create-quiz-zone.dto.ts
apps/frontend/src/utils/validators.ts

fix: 부하 테스트를 위한 입장 인원 제한 제거

---

apps/frontend/vite.config.ts

chore: 디렉토리 경로 clean 옵션 추가

---

apps/frontend/src/hook/useTimer.ts

feat: webWorker 쿼리 추가

---

apps/frontend/src/hook/useTimer.ts
apps/frontend/src/workers/timer.worker.ts

- staging 환경 web worker 실행 이슈 수정

fix: worker 파일 형식 수정

---

apps/frontend/src/blocks/QuizZone/QuizZoneLobby.tsx
apps/frontend/src/pages/QuizZonePage.tsx

fix: 방장 종료창 노출 조건 추가
